# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "70183982e9914bf4b2a21999b848ba48"
name = "pragmatic-outsource-app"
application_url = "https://comply-contained-detect-trader.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bossbeanzv2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://comply-contained-detect-trader.trycloudflare.com/auth/callback",
  "https://comply-contained-detect-trader.trycloudflare.com/auth/shopify/callback",
  "https://comply-contained-detect-trader.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
