# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9ce44668598513b59e4b672aff9ccb33"
name = "kitchen-sink"
handle = "kitchen-sink-7"
application_url = "https://banners-disagree-relation-farms.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3a22a586.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://banners-disagree-relation-farms.trycloudflare.com/auth/callback",
  "https://banners-disagree-relation-farms.trycloudflare.com/auth/shopify/callback",
  "https://banners-disagree-relation-farms.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
