# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "755ffc4f46928602fc63d026b7633bbc"
name = "hot-tricks-from-dev-docs"
handle = "hot-tricks-from-dev-docs"
application_url = "https://cathedral-together-labor-infant.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bossbeanzv2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_delivery_customizations,write_discounts,write_discounts_allocator_functions,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://cathedral-together-labor-infant.trycloudflare.com/auth/callback",
  "https://cathedral-together-labor-infant.trycloudflare.com/auth/shopify/callback",
  "https://cathedral-together-labor-infant.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
