# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "44bbb44225b104c4930a5d283e3c94c5"
name = "hot-tricks-from-dev-docs"
application_url = "https://peoples-discusses-easily-advertisement.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bossbeanzv2.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://peoples-discusses-easily-advertisement.trycloudflare.com/auth/callback",
  "https://peoples-discusses-easily-advertisement.trycloudflare.com/auth/shopify/callback",
  "https://peoples-discusses-easily-advertisement.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
